#!/usr/bin/env python3
"""Capture real QML presets and merge them into a few high-resolution sheets.

Run `make gallery` in the Qt development shell. No image processing dependencies:
the sheets are laid out and rendered by QML itself, so nothing is rescaled or
recompressed. Software works headlessly; use --backend opengl for shader effects.
"""

import argparse
import json
import os
import re
import shutil
import struct
import subprocess
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# Every preset lives on exactly one sheet, grouped so that a sheet holds widgets
# of a similar size and mood. Two columns keep the images readable on a phone.
# The last field zooms a sheet whose widgets are too small to read on their own.
SHEETS = [
    (
        "sheet-cards",
        "Classic cards",
        "sea",
        2,
        ("classic", "glass", "cover", "neon"),
        1,
    ),
    (
        "sheet-surfaces",
        "Surfaces & players",
        "sea",
        2,
        ("solid", "cd", "vinyl", "arcade"),
        1,
    ),
    (
        "sheet-stacked",
        "Stacked glass",
        "sea",
        2,
        ("liquid", "quiet", "atmos", "lyrics"),
        1,
    ),
    (
        "sheet-posters",
        "Posters & heroes",
        "sea",
        2,
        ("poster", "posterhang", "stalactite", "hero"),
        1,
    ),
    (
        "sheet-orbits",
        "Orbits & lyrics",
        "sea",
        2,
        ("orbit", "halo", "sunburst", "lyricsonly"),
        1,
    ),
    (
        "sheet-minimal",
        "Slim & minimal",
        "sea",
        2,
        ("strip", "mirror", "compact", "ribbon"),
        1,
    ),
    (
        "sheet-panels",
        "Panel layouts",
        "sea",
        2,
        ("panelpill", "ribbonpill", "baricon", "orbiticon"),
        2,
    ),
]

# Kept as single captures because the README opens with them.
FEATURED = ("classic", "liquid")

PRESET_PATTERN = re.compile(
    r'^\s+preset\("([\w-]+)",\s*\[[^\]]*\],\s*"([^"]*)",\s*"([^"]*)"', re.MULTILINE
)


def presets(schema):
    found = [
        {"id": i, "title": t, "description": d}
        for i, t, d in PRESET_PATTERN.findall(schema)
    ]
    if not found:
        raise RuntimeError("No presets found")
    return found


def check_sheets(ids):
    placed = [i for *_, members, _ in SHEETS for i in members]
    missing = [i for i in ids if i not in placed]
    unknown = [i for i in placed if i not in ids]
    if missing or unknown:
        raise RuntimeError(
            f"Sheets are out of date — missing: {missing}, unknown: {unknown}"
        )
    if len(set(placed)) != len(placed):
        raise RuntimeError("A preset appears on more than one sheet")


def png_size(path, name):
    data = path.read_bytes()
    if data[:8] != b"\x89PNG\r\n\x1a\n":
        raise RuntimeError(f"Invalid PNG: {name}")
    width, height = struct.unpack(">II", data[16:24])
    if min(width, height) < 100:
        raise RuntimeError(f"Capture is not high resolution: {name} {width}x{height}")
    return [width, height]


def write_gallery(path, catalogue, dimensions):
    lines = [
        "<!-- Generated by tools/capture_gallery.py; run `make gallery`. -->",
        "",
        "# Preset gallery",
        "",
        "Real QML screenshots with fixed sample audio and the original 1024px",
        "widget icon. Each sheet is one capture: the presets are rendered together",
        "at 2× resolution on a shared wallpaper, so nothing here is rescaled or",
        "pasted together afterwards.",
        "",
        "Rebuild with `make gallery`. These captures use Qt’s software renderer;",
        "GPU-only blur, reflection and shader effects are omitted. For OpenGL",
        "captures on a desktop, run",
        '`make gallery GALLERY_FLAGS="--backend opengl --platform wayland"`.',
        "",
    ]
    for name, title, _, _, members, _ in SHEETS:
        width, _height = dimensions[name]
        lines += [
            f"## {title}",
            "",
            (
                f'<img src="../readme/{name}.png" width="{width // 2}" '
                f'alt="{title} — real QML screenshot">'
            ),
            "",
        ]
        for member in members:
            preset = catalogue[member]
            lines.append(f"- **{preset['title']}** — {preset['description']}")
        lines.append("")
    path.write_text("\n".join(lines))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=ROOT / "readme")
    parser.add_argument("--backend", choices=("opengl", "software"), default="software")
    parser.add_argument("--platform", default="offscreen")
    args = parser.parse_args()
    runner = shutil.which("qmltestrunner")
    if not runner:
        parser.error("Qt 6 qmltestrunner must be on PATH (use the development shell)")
    output = args.output.resolve()
    output.mkdir(parents=True, exist_ok=True)
    ui = ROOT / "package/contents/ui"
    schema = (ui / "studio/Schema.js").read_text()
    catalogue = {p["id"]: p for p in presets(schema)}
    check_sheets(catalogue)
    with tempfile.TemporaryDirectory(prefix="audio-gallery-") as directory:
        staging = Path(directory)
        template = (ROOT / "readme/Capture.qml.in").read_text()
        values = {
            "UI": ui.as_uri(),
            "STUDIO": (ui / "studio").as_uri(),
            "SCHEMA": (ui / "studio/Schema.js").as_uri(),
            "LAYOUTS": (ROOT / "package/contents/code/Layouts.js").as_uri(),
            "CONFIG": (ROOT / "hyprland/Configuration.js").as_uri(),
            "XML": (ROOT / "package/contents/config/main.xml").as_uri(),
            "OUTPUT": str(staging),
            "SHEETS": [
                {
                    "id": i,
                    "title": t,
                    "bd": bd,
                    "columns": c,
                    "members": list(m),
                    "zoom": z,
                }
                for i, t, bd, c, m, z in SHEETS
            ],
        }
        for key, value in values.items():
            template = template.replace(f"@{key}@", json.dumps(value))
        qml = staging / "tst_gallery.qml"
        qml.write_text(template)
        env = os.environ | {
            "QT_QPA_PLATFORM": args.platform,
            "QT_QPA_PLATFORMTHEME": "generic",
            "QT_QUICK_CONTROLS_STYLE": "Basic",
            "QT_SCALE_FACTOR": "1",
            "QT_FONT_DPI": "96",
            "QML_XHR_ALLOW_FILE_READ": "1",
            "QML_DISABLE_DISK_CACHE": "1",
            "QT_QUICK_BACKEND": "software" if args.backend == "software" else "rhi",
            "QSG_RHI_BACKEND": "opengl",
        }
        subprocess.run(
            [runner, "-input", str(qml), "-import", str(ROOT / "tests/stubs")],
            env=env,
            check=True,
            timeout=300,
        )
        if (ui / "studio/Schema.js").read_text() != schema:
            raise RuntimeError(
                "Presets changed during capture; rerun with a stable source tree"
            )
        # Every preset is still rendered on its own first, so a broken layout fails
        # the run even when its sheet happens to look fine.
        for name in catalogue:
            png_size(staging / f"{name}.png", name)
        published = [s[0] for s in SHEETS] + list(FEATURED) + ["studio"]
        dimensions = {
            name: png_size(staging / f"{name}.png", name) for name in published
        }
        # Publish only after the entire capture succeeds and validates.
        for name in dimensions:
            shutil.copyfile(staging / f"{name}.png", output / f"{name}.png")
    for stale in sorted(output.glob("*.png")):
        if stale.stem not in dimensions and stale.stem in catalogue:
            stale.unlink()
    (output / "captures.json").write_text(
        json.dumps(
            {
                "backend": args.backend,
                "scale": 2,
                "images": dimensions,
            },
            indent=2,
        )
        + "\n"
    )
    write_gallery(ROOT / "docs/gallery.md", catalogue, dimensions)
    print(
        f"Captured {len(SHEETS)} sheets covering {len(catalogue)} presets in {output}"
    )


if __name__ == "__main__":
    main()
