#!/usr/bin/env python3
"""Publish the QML studio catalogue/wallpapers into the standalone Pages tree.

Run without arguments after editing canonical assets; --check detects drift in CI.
"""

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "package/contents/ui/studio"
DEST = ROOT / "docs/website/assets/studio"


def outputs():
    catalog = (SOURCE / "StudioCatalog.js").read_bytes()
    data = json.loads(
        catalog.decode().split("var StudioCatalog = ", 1)[1].rstrip().removesuffix(";")
    )
    result = {
        "StudioCatalog.js": catalog,
        "PresetCodec.js": (SOURCE / "PresetCodec.js").read_bytes(),
        "icon.png": (ROOT / "package/icon.png").read_bytes(),
    }
    css = [
        "/* Generated by tools/sync_studio_assets.py; edit the studio catalogue. */",
        ".bd{background-size:cover;background-position:center;background-repeat:no-repeat}",
    ]
    # QML uses ARGB; CSS uses RGBA. Keep one palette in the catalogue.
    palette = []
    for name, value in data["theme"].items():
        if not value.startswith("#"):
            continue
        if len(value) == 9:
            value = "#" + value[3:] + value[1:3]
        palette.append(f"--studio-{name}:{value}")
    css.append(":root{" + ";".join(palette) + "}")
    for wallpaper in data["wallpapers"]:
        filename = wallpaper["file"]
        assert Path(filename).name == filename, (
            "Wallpaper filenames must be local basenames"
        )
        result["wallpapers/" + filename] = (
            SOURCE / "wallpapers" / filename
        ).read_bytes()
        css.append(
            f".bd-{wallpaper['id']}"
            + "{background-color:"
            + wallpaper["color"]
            + ';background-image:url("wallpapers/'
            + filename
            + '")}'
        )
    result["wallpapers.css"] = ("\n".join(css) + "\n").encode()
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    mismatches = []
    for name, content in outputs().items():
        target = DEST / name
        if args.check:
            if not target.exists() or target.read_bytes() != content:
                mismatches.append(name)
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(content)
    if mismatches:
        raise SystemExit(
            "Studio assets need syncing: "
            + ", ".join(mismatches)
            + ". Run python3 tools/sync_studio_assets.py"
        )
    print(
        "PASS: shared studio assets are identical"
        if args.check
        else "Updated shared studio assets for Pages"
    )


if __name__ == "__main__":
    main()
